### ISSUE TITLE
Customizing favicon and add google analytics

### ISSUE THREAD

**Issue by dd-jy** [rundocs/starter#1]
Hi,

I want to use this rundocs theme.
But I want to add my favicon image and google anlytics tracking id.
How can I do it?
Please reply to me.

Thanks!

**Comment by saowang** [comment]
https://rundocs.io/configuring/analytics.html

**Comment by saowang** [comment]
current favicon can overwrite, custom option will comming soon in next version!

thanks

**Comment by dd-jy** [comment]
Thank you for your quick reply!
When do you plan to release the next version?

**Comment by saowang** [comment]
You can check the debug branch of the theme, maybe this weekend，current you fork and modify

**Comment by dd-jy** [comment]
Thank you!
